
//USERS

###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "John5@gmail.com",
  "password": "A12345678",
  "name": "John4"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "John5@gmail.com",
  "password": "123456"
}

###
POST http://localhost:8080/auth/logout
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJqdGkiOiIxIiwibmFtZSI6Inp6eiIsInN1YiI6ImFhYSIsImlhdCI6MTc0MjMwNjUyMSwiZXhwIjoxNzQyMzkyOTIxfQ.tuGps1EYXuc2nK1Nhzq3p67v7WSwIqkDIjaTx7Hu7Dr8SQxtod7WCnZOepyXTG1j

###
PUT http://localhost:8080/api/user/credentials
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJqdGkiOiIxIiwibmFtZSI6IkpvaG40Iiwic3ViIjoiSm9objVAZ21haWwuY29tIiwiaWF0IjoxNzQ1MzYwOTg0LCJleHAiOjE3NDU0NDczODR9.x3_pzQXrGQZKIJ84-1WvBFtvp0AXHM6MQrRTDcWJjq9mRye-owvgv2sSLK9YHiD6
Content-Type: application/json

{
  "address": "0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1",
  "key": "0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d"
}

###
GET http://localhost:8080/api/user
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJqdGkiOiIxIiwibmFtZSI6IkpvaG40Iiwic3ViIjoiSm9objVAZ21haWwuY29tIiwiaWF0IjoxNzQ1MzU4NzY1LCJleHAiOjE3NDU0NDUxNjV9.CWM7V6Ql60gQYtsbu3wpgxS3LH9xbh6jk3XKndp5HrriXWtN4BAYF8cax2h32DxW


//SHIPMENTS

###
POST http://localhost:8080/api/shipment/create
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJqdGkiOiIxIiwibmFtZSI6IkpvaG40Iiwic3ViIjoiSm9objVAZ21haWwuY29tIiwiaWF0IjoxNzQ1MzU5MDEwLCJleHAiOjE3NDU0NDU0MTB9.1BS5Sfrrg_67_k_wrh49cVUqPtorRz9fPDG-nPm3CYhrJODx_MfqObabYwaRQ2fF
Content-Type: application/json

{
  "productName": "Vaccine",
  "description": "pfizer",
  "origin": "Sant Pol de Mar",
  "destination": "Brazil",
  "deliveryDate": "2025-05-05",
  "units": 2,
  "weight": 2
}

###
GET http://localhost:8080/api/shipment/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJqdGkiOiIxIiwibmFtZSI6IkpvaG40Iiwic3ViIjoiSm9objVAZ21haWwuY29tIiwiaWF0IjoxNzQ1MzU4NzY1LCJleHAiOjE3NDU0NDUxNjV9.CWM7V6Ql60gQYtsbu3wpgxS3LH9xbh6jk3XKndp5HrriXWtN4BAYF8cax2h32DxW

###
GET http://localhost:8080/api/shipment/nextId
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJqdGkiOiIxIiwibmFtZSI6IkpvaG40Iiwic3ViIjoiSm9objVAZ21haWwuY29tIiwiaWF0IjoxNzQ0NzIwNDgxLCJleHAiOjE3NDQ4MDY4ODF9.mwbuJ8_zVQSXYqhoXspyzWIX_vXAZxRQ8CGek0xXpy40My5bNLv7Z30vlyZE7nrw

//TRANSFERS

###
POST http://localhost:8080/api/transfer/create
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJqdGkiOiIxIiwibmFtZSI6IkpvaG40Iiwic3ViIjoiSm9objVAZ21haWwuY29tIiwiaWF0IjoxNzQ1MzU5MDEwLCJleHAiOjE3NDU0NDU0MTB9.1BS5Sfrrg_67_k_wrh49cVUqPtorRz9fPDG-nPm3CYhrJODx_MfqObabYwaRQ2fF
Content-Type: application/json

{
  "shipmentId": 2,
  "newShipmentOwner": "1",
  "newState": 1,
  "location": "SAMBA3",
  "transferNotes": "Transferred to your address"
}

###
GET http://localhost:8080/api/transfer/2
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJqdGkiOiIxIiwibmFtZSI6IkpvaG40Iiwic3ViIjoiSm9objVAZ21haWwuY29tIiwiaWF0IjoxNzQ1MzU5MDEwLCJleHAiOjE3NDU0NDU0MTB9.1BS5Sfrrg_67_k_wrh49cVUqPtorRz9fPDG-nPm3CYhrJODx_MfqObabYwaRQ2fF

###
GET http://localhost:8080/api/transfer/nextId
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJqdGkiOiIxIiwibmFtZSI6IkpvaG40Iiwic3ViIjoiSm9objVAZ21haWwuY29tIiwiaWF0IjoxNzQ0NzIwNDgxLCJleHAiOjE3NDQ4MDY4ODF9.mwbuJ8_zVQSXYqhoXspyzWIX_vXAZxRQ8CGek0xXpy40My5bNLv7Z30vlyZE7nrw

//RECCORDS

###
GET http://localhost:8080/api/records/shipment/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJqdGkiOiIxIiwibmFtZSI6IkpvaG4zIiwic3ViIjoiSm9objJAZ21haWwuY29tIiwiaWF0IjoxNzQzNTA5Mzk0LCJleHAiOjE3NDM1OTU3OTR9.t5_bFKzd3uKBNyGaJMHg9QYFBwQdsOhUgKYXgU5W7KZLCnItojmAPa897c1kS079

###
GET http://localhost:8080/api/records/stats

###
GET http://localhost:8080/api/records/participant
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJqdGkiOiIxIiwibmFtZSI6IkpvaG40Iiwic3ViIjoiSm9objVAZ21haWwuY29tIiwiaWF0IjoxNzQ0ODIxMDM0LCJleHAiOjE3NDQ5MDc0MzR9.DVaUL2IB5zwDQFNJH_b1nmaY0jUFfoJFrYbFsNULaw6z462TD6ZsTnlOLCgiSToV

###
GET http://localhost:8080/api/records/owner
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJqdGkiOiIxIiwibmFtZSI6IkpvaG40Iiwic3ViIjoiSm9objVAZ21haWwuY29tIiwiaWF0IjoxNzQ0ODIxMDM0LCJleHAiOjE3NDQ5MDc0MzR9.DVaUL2IB5zwDQFNJH_b1nmaY0jUFfoJFrYbFsNULaw6z462TD6ZsTnlOLCgiSToV

//NOTIFICATIONS

###
GET http://localhost:8080/api/notification
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJqdGkiOiIyIiwibmFtZSI6IkpvaG40Iiwic3ViIjoiSm9objRAZ21haWwuY29tIiwiaWF0IjoxNzQ0MzE0MDE3LCJleHAiOjE3NDQ0MDA0MTd9.rxBTm-MQ7q_dPaBS3m8pBF7VYTJKgoIrawrRMM3ir3t8-14pMbp3PlQlEb27utMB

###
PATCH http://localhost:8080/api/notification/read/2
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJqdGkiOiIxIiwibmFtZSI6IkpvaG4zIiwic3ViIjoiSm9objNAZ21haWwuY29tIiwiaWF0IjoxNzQ0MzEzODcyLCJleHAiOjE3NDQ0MDAyNzJ9.tKEvqP52Dcqag59ZoqKqUi17a5hSgCLPj01R-0Go-2m09tU2nw0kIOkL37BOUQ9k

