//BLOCKCHAIN

###
POST http://localhost:8080/blockchain

###
GET http://localhost:8080/blockchain/blockNumber

//USERS

###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "John2@gmail.com",
  "password": "123456",
  "name": "John3"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "John2@gmail.com",
  "password": "123456"
}

###
POST http://localhost:8080/auth/logout
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJqdGkiOiIxIiwibmFtZSI6Inp6eiIsInN1YiI6ImFhYSIsImlhdCI6MTc0MjMwNjUyMSwiZXhwIjoxNzQyMzkyOTIxfQ.tuGps1EYXuc2nK1Nhzq3p67v7WSwIqkDIjaTx7Hu7Dr8SQxtod7WCnZOepyXTG1j

###
PUT http://localhost:8080/api/user/credentials
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJqdGkiOiIxIiwibmFtZSI6IkpvaG4zIiwic3ViIjoiSm9objJAZ21haWwuY29tIiwiaWF0IjoxNzQzNTA5MDgyLCJleHAiOjE3NDM1OTU0ODJ9.Qh5C6xVWz82d9lW7AMg-2Nzj1-LcZKu75_5Us_wlgmUZRWE8rVZwDd36UuCE-ny4
Content-Type: application/json

{
  "address": "0xE11BA2b4D45Eaed5996Cd0823791E0C93114882d",
  "key": "0x646f1ce2fdad0e6deeeb5c7e8e5543bdde65e86029e2fd9fc169899c440a7913"
}

###
GET http://localhost:8080/api/user
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJqdGkiOiIxIiwibmFtZSI6IkpvaG4zIiwic3ViIjoiSm9objJAZ21haWwuY29tIiwiaWF0IjoxNzQyNzUyNzk4LCJleHAiOjE3NDI4MzkxOTh9.eYaN1uXR-XMTttxQpkQcxWUNckmAjmksHeDByAIcCwf6nkdL5xyhr3X_8wTy5OkM


//SHIPMENTS

###
POST http://localhost:8080/api/shipment/create
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJqdGkiOiIxIiwibmFtZSI6IkpvaG4zIiwic3ViIjoiSm9objJAZ21haWwuY29tIiwiaWF0IjoxNzQyNzUzNjYyLCJleHAiOjE3NDI4NDAwNjJ9.9QYvLKhO9bdO1FkUD1sEkb7ke1SLmPvGvDBcIvGb9zIoKYIZMZuOqn9-6ma9TlsE
Content-Type: application/json

{
  "name": "Vaccine3",
  "description": "pfizer",
  "origin": "Sant Pol de Mar",
  "destination": "Brazil",
  "units": 2,
  "weight": 2
}

###
GET http://localhost:8080/api/shipment/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJqdGkiOiIxIiwibmFtZSI6IkpvaG4zIiwic3ViIjoiSm9objJAZ21haWwuY29tIiwiaWF0IjoxNzQyNzUzNjYyLCJleHAiOjE3NDI4NDAwNjJ9.9QYvLKhO9bdO1FkUD1sEkb7ke1SLmPvGvDBcIvGb9zIoKYIZMZuOqn9-6ma9TlsE

###
GET http://localhost:8080/api/shipment/nextId
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJqdGkiOiIxIiwibmFtZSI6IkpvaG4zIiwic3ViIjoiSm9objJAZ21haWwuY29tIiwiaWF0IjoxNzQyNzUyNzk4LCJleHAiOjE3NDI4MzkxOTh9.eYaN1uXR-XMTttxQpkQcxWUNckmAjmksHeDByAIcCwf6nkdL5xyhr3X_8wTy5OkM

//TRANSFERS

###
POST http://localhost:8080/api/transfer/create
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJqdGkiOiIxIiwibmFtZSI6IkpvaG4zIiwic3ViIjoiSm9objJAZ21haWwuY29tIiwiaWF0IjoxNzQyNzUzNjYyLCJleHAiOjE3NDI4NDAwNjJ9.9QYvLKhO9bdO1FkUD1sEkb7ke1SLmPvGvDBcIvGb9zIoKYIZMZuOqn9-6ma9TlsE
Content-Type: application/json

{
  "shipmentId": 1,
  "newShipmentOwner": 1,
  "newState": 3,
  "location": "SAMBA2",
  "transferNotes": "Transferred to new warehouse"
}

###
GET http://localhost:8080/api/transfer/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJqdGkiOiIxIiwibmFtZSI6IkpvaG4iLCJzdWIiOiJKb2huQGdtYWlsLmNvbSIsImlhdCI6MTc0MjM0NTc4NCwiZXhwIjoxNzQyNDMyMTg0fQ.Ks73u_riS9vHnPZQ7n32OsXJ8pvluBgF96cM-21EZsfUhon9WeEMoYnrcZbR2cWm

###
GET http://localhost:8080/api/transfer/nextId
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJqdGkiOiIxIiwibmFtZSI6IkpvaG4iLCJzdWIiOiJKb2huQGdtYWlsLmNvbSIsImlhdCI6MTc0MjM0NDMwNCwiZXhwIjoxNzQyNDMwNzA0fQ.l4D04_y1rdjJN2F83k3smtw0B5YEITvjsVWSJwa4kMjRX9i7_UW9eRTB6991e2Kj

//RECCORDS

###
GET http://localhost:8080/api/records/shipment/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJqdGkiOiIxIiwibmFtZSI6IkpvaG4zIiwic3ViIjoiSm9objJAZ21haWwuY29tIiwiaWF0IjoxNzQzNTA5Mzk0LCJleHAiOjE3NDM1OTU3OTR9.t5_bFKzd3uKBNyGaJMHg9QYFBwQdsOhUgKYXgU5W7KZLCnItojmAPa897c1kS079

###
GET http://localhost:8080/api/records/stats

###
GET http://localhost:8080/api/records/participant
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJqdGkiOiIyIiwibmFtZSI6IkpvaG4yIiwic3ViIjoiSm9objJAZ21haWwuY29tIiwiaWF0IjoxNzQyMzQ2MTI5LCJleHAiOjE3NDI0MzI1Mjl9.AyH3rAXvpRi268OWbT0xaVunsrGLRnwrjO3qg_2hTUxP6bXn1AGB7asV69_UUnNV

###
GET http://localhost:8080/api/records/owner
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJqdGkiOiIxIiwibmFtZSI6IkpvYW4iLCJzdWIiOiJhYWFAYWFhIiwiaWF0IjoxNzQyMzg4OTk3LCJleHAiOjE3NDI0NzUzOTd9.mDHdpF-FmOyV7Vo_kgi7da9qr6iQBt5Q1ocAubmK1Tt5HqVgYD_ANX9GQwo3c5Lo

